# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-01 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('judul', models.CharField(max_length=140)),
                ('konten_short', models.CharField(max_length=140)),
                ('konten', models.TextField()),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArtikelRekomendasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('judul', models.CharField(max_length=140)),
                ('konten_short', models.CharField(max_length=140)),
                ('konten', models.TextField()),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPortofolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('nama', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('noHp', models.CharField(max_length=140)),
                ('kelamin', models.CharField(max_length=140)),
                ('birth', models.CharField(max_length=140)),
                ('alamat', models.CharField(max_length=300)),
                ('domisili', models.CharField(max_length=140)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoDonasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorUnitBisnis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='KegiatanVolunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('judul', models.CharField(max_length=140)),
                ('konten_short', models.CharField(max_length=140)),
                ('konten', models.TextField()),
                ('tags', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konten', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('konten', models.TextField()),
                ('nama', models.TextField(max_length=140)),
                ('jabatan', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('konten', models.TextField()),
                ('nama', models.TextField(max_length=140)),
                ('jabatan', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('konten', models.TextField()),
                ('nama', models.TextField(max_length=140)),
                ('jabatan', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UnitBisnis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaFile', models.TextField()),
                ('urlFoto', models.URLField()),
                ('judul', models.CharField(max_length=140)),
                ('konten', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=140)),
                ('nama', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('noHp', models.CharField(max_length=140)),
                ('kelamin', models.CharField(max_length=140)),
                ('birth', models.CharField(max_length=140)),
                ('alamat', models.TextField()),
                ('domisili', models.CharField(max_length=140)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='indikatorunitbisnis',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakafapp.UnitBisnis'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakafapp.Parent'),
        ),
    ]
