# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-29 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wakafapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatur',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 2, 21, 23, 430801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 2, 21, 23, 437306, tzinfo=utc)),
        ),
    ]
