# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-02 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakafapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='judul',
            field=models.CharField(default='null', max_length=140),
            preserve_default=False,
        ),
    ]
